---
version: "3.9"
services:
  web:
    build: .
    environment:
      - TERM=xterm
    command: sh -c "bundle exec puma"
    volumes:
      - /home/nina/Sync/code/URbooks/tmp/urbooks:/home/urbooks/.config/urbooks
      #- /home/nina/Sync/code/URbooks/tmp/audiobooks:/home/urbooks/audiobooks
      #- /home/nina/Sync/code/URbooks/tmp/podfics:/home/urbooks/podfics
      - audiobooks:/home/urbooks/audiobooks
      - podfics:/home/urbooks/podfics
    ports:
      - "9292:9292"

volumes:
  audiobooks:
    driver: rclone:latest
    driver_opts:
      allow_other: 'true'
      vfs_cache_mode: full
      read_only: 'true'
      remote: 'audiobooks:'
      pcloud_client_id: AXlSAwlucVj
      pcloud_client_secret: uBXvEzTpV3JMcbd3xqbYsFXSAqCy
      pcloud_token: '{"access_token":"2Ci6ZAXlSAwlucVjZv8lRG7Zm2UqEuGya9Y7zH7gRA9rALGWyBHy","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}'
      pcloud_root_folder_id: 10261500678
  podfics:
    driver: rclone:latest
    driver_opts:
      allow_other: 'true'
      vfs_cache_mode: full
      read_only: 'true'
      remote: 'podfics:'
      pcloud_client_id: AXlSAwlucVj
      pcloud_client_secret: uBXvEzTpV3JMcbd3xqbYsFXSAqCy
      pcloud_token: '{"access_token":"2Ci6ZAXlSAwlucVjZv8lRG7Zm2UqEuGya9Y7zH7gRA9rALGWyBHy","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}'
      pcloud_root_folder_id: 11340422822
